# Generated by Django 4.0.4 on 2022-05-18 11:42
from __future__ import annotations

import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='post',
            name='extract_ar',
            field=models.TextField(blank=True, help_text='Small extract of your video', max_length=200, null=True, verbose_name='Extract'),
        ),
        migrations.AddField(
            model_name='post',
            name='extract_en',
            field=models.TextField(blank=True, help_text='Small extract of your video', max_length=200, null=True, verbose_name='Extract'),
        ),
        migrations.AddField(
            model_name='post',
            name='extract_fr',
            field=models.TextField(blank=True, help_text='Small extract of your video', max_length=200, null=True, verbose_name='Extract'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
    ]
